stages:
  prepare_data:
    cmd: python src/data_preparation.py
    deps:
    - data/raw
    - src/config.py
    outs:
    - data/processed
  augment_data:
    cmd: python src/data_augmentation.py
    deps:
    - data/processed
    - src/config.py
    outs:
    - data/augmented
  train_model:
    cmd: python src/train.py
    deps:
    - data/augmented
    - data/processed
    - src/config.py
