name: Data validation with deepchecks

on:
  push:
    branches: [ main ]
    paths:
      - data/processed/**
      - data/augmented/**
      - src/data_preparation.py
      - src/data_augmentation.py
      - dvc.lock
  pull_request:
    branches: [ main ]
    paths:
      - data/processed/**
      - data/augmented/**
      - src/data_preparation.py
      - src/data_augmentation.py
      - dvc.lock

permissions: write-all

jobs:
  run_data_checks:

    runs-on: ubuntu-latest
    env:
      DVC_USERNAME: ${{ secrets.DVC_USERNAME }}
      DVC_PASSWORD: ${{ secrets.DVC_PASSWORD }}

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        cache: pip

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/dev-requirements.txt') }}
        restore-keys: ${{ runner.os }}-pip-

    - name: Install dependencies
      run: pip install -r dev-requirements.txt
    
    - name: Get data
      run: |
        dvc remote modify origin --local auth basic
        dvc remote modify origin --local user $DVC_USERNAME
        dvc remote modify origin --local password $DVC_PASSWORD
        dvc pull -v -r origin
    
    - name: Remove the old validation reports
      run: |
        rm -rf data_validation
        mkdir data_validation
        
    - name: Validate data with deepchecks
      run: |
        python src/data_preparation.py
        python src/data_augmentation.py
        python src/data_validation.py
    
    - name: Commit the validation report file
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Added data validation reports
        
    - name: Create a comment
      uses: peter-evans/commit-comment@v1
      with:
        body: |
          Please check data validation reports.
